name: stereoset
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - arrow-cpp=16.1.0=hc1eb8f0_0
  - async-timeout=4.0.3=py310h06a4308_0
  - aws-c-auth=0.6.19=h5eee18b_0
  - aws-c-cal=0.5.20=hdbd6064_0
  - aws-c-common=0.8.5=h5eee18b_0
  - aws-c-compression=0.2.16=h5eee18b_0
  - aws-c-event-stream=0.2.15=h6a678d5_0
  - aws-c-http=0.6.25=h5eee18b_0
  - aws-c-io=0.13.10=h5eee18b_0
  - aws-c-mqtt=0.7.13=h5eee18b_0
  - aws-c-s3=0.1.51=hdbd6064_0
  - aws-c-sdkutils=0.1.6=h5eee18b_0
  - aws-checksums=0.1.13=h5eee18b_0
  - aws-crt-cpp=0.18.16=h6a678d5_0
  - aws-sdk-cpp=1.10.55=h721c034_0
  - blas=1.0=openblas
  - boost-cpp=1.82.0=hdb19cb5_2
  - bottleneck=1.3.7=py310ha9d4c09_0
  - brotli-python=1.0.9=py310hd8f1fbe_7
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.7.4=hbcca054_0
  - certifi=2024.7.4=py310h06a4308_0
  - cffi=1.17.0=py310h2fdcea3_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - filelock=3.15.4=pyhd8ed1ab_0
  - frozenlist=1.4.1=py310h2372a71_0
  - fsspec=2024.6.1=pyhff2d567_0
  - gflags=2.2.2=h6a678d5_1
  - glog=0.5.0=h6a678d5_1
  - h2=4.1.0=pyhd8ed1ab_0
  - hpack=4.0.0=pyh9f0ad1d_0
  - huggingface_hub=0.24.6=pyhd8ed1ab_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=73.1=h6a678d5_0
  - idna=3.7=pyhd8ed1ab_0
  - importlib-metadata=8.4.0=pyha770c72_0
  - krb5=1.20.1=h143b758_1
  - ld_impl_linux-64=2.38=h1181459_1
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libboost=1.82.0=h109eef0_2
  - libbrotlicommon=1.0.9=h5eee18b_8
  - libbrotlidec=1.0.9=h5eee18b_8
  - libbrotlienc=1.0.9=h5eee18b_8
  - libcurl=8.7.1=h251f7ec_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=14.1.0=h77fa898_0
  - libgfortran=3.0.0=1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=14.1.0=h77fa898_0
  - libgrpc=1.62.2=h2d74bed_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libopenblas=0.3.21=h043d6bf_0
  - libprotobuf=4.25.3=he621ea3_0
  - libssh2=1.11.0=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libthrift=0.15.0=h1795dd8_2
  - libuuid=1.41.5=h5eee18b_0
  - lz4-c=1.9.4=h6a678d5_1
  - multidict=6.0.5=py310h2372a71_0
  - ncurses=6.4=h6a678d5_0
  - numexpr=2.8.7=py310h286c3b5_0
  - openblas=0.3.4=ha44fe06_0
  - openssl=3.3.1=h4bc722e_2
  - orc=2.0.1=h2d29ad5_0
  - packaging=24.1=pyhd8ed1ab_0
  - pandas=2.2.2=py310h6a678d5_0
  - pip=24.0=py310h06a4308_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.10.14=h955ad1f_1
  - python-dateutil=2.9.0post0=py310h06a4308_2
  - python_abi=3.10=2_cp310
  - pytz=2024.1=py310h06a4308_0
  - pyyaml=6.0.2=py310h5b4e0ec_0
  - re2=2022.04.01=h295c915_0
  - readline=8.2=h5eee18b_0
  - regex=2024.7.24=py310h5eee18b_0
  - requests=2.32.3=pyhd8ed1ab_0
  - s2n=1.3.27=hdbd6064_0
  - safetensors=0.4.4=py310h42e942d_0
  - setuptools=69.5.1=py310h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.2.1=h6a678d5_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - tokenizers=0.19.1=py310hff361bb_0
  - transformers=4.44.1=pyhd8ed1ab_0
  - typing-extensions=4.12.2=hd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - utf8proc=2.6.1=h5eee18b_1
  - wheel=0.43.0=py310h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7f98852_2
  - yarl=1.9.4=py310h2372a71_0
  - zipp=3.20.1=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_1
  - zstandard=0.22.0=py310h1275a96_0
  - zstd=1.5.5=hc292b87_2
  - pip:
      - accelerate==0.34.2
      - aiohappyeyeballs==2.3.6
      - aiohttp==3.10.3
      - alabaster==0.7.16
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyascii==0.3.2
      - anyio==4.5.0
      - asttokens==2.4.1
      - attrs==24.2.0
      - babel==2.16.0
      - cachetools==5.4.0
      - click==8.1.7
      - cloudpickle==3.0.0
      - coloredlogs==15.0.1
      - contractions==0.1.73
      - datasets==2.2.1
      - decorator==5.1.1
      - dill==0.3.8
      - diskcache==5.6.3
      - distro==1.9.0
      - docformatter==1.4
      - docutils==0.15.2
      - einops==0.8.0
      - emoji==2.12.1
      - exceptiongroup==1.2.2
      - executing==2.0.1
      - fairscale==0.4.13
      - fastapi==0.115.0
      - flake8==7.1.1
      - flake8-bugbear==24.4.26
      - fuzzywuzzy==0.18.0
      - gguf==0.9.1
      - gitdb==4.0.11
      - gitdb2==4.0.2
      - gitpython==3.1.43
      - google-api-core==2.11.0
      - google-auth==2.33.0
      - google-cloud-core==2.4.1
      - google-cloud-storage==2.14.0
      - google-crc32c==1.5.0
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.63.2
      - h11==0.14.0
      - httpcore==1.0.5
      - httptools==0.6.1
      - httpx==0.27.2
      - humanfriendly==10.0
      - hydra-core==1.3.2
      - imagesize==1.4.1
      - iniconfig==2.0.0
      - interegular==0.3.3
      - iopath==0.1.10
      - ipython==8.26.0
      - jedi==0.19.1
      - jinja2==3.1.4
      - jiter==0.5.0
      - joblib==1.4.2
      - jsonlines==4.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - lark==1.2.2
      - llvmlite==0.43.0
      - lm-format-enforcer==0.10.6
      - markdown==3.3.2
      - markdown-it-py==2.2.0
      - markupsafe==2.1.5
      - matplotlib-inline==0.1.7
      - mccabe==0.7.0
      - mdit-py-plugins==0.3.5
      - mdurl==0.1.2
      - mistral-common==1.4.2
      - mock==5.1.0
      - mpmath==1.3.0
      - msgpack==1.1.0
      - msgspec==0.18.6
      - multiprocess==0.70.16
      - myst-parser==0.19.2
      - nest-asyncio==1.6.0
      - networkx==3.3
      - ninja==1.10.2.4
      - nltk==3.8.1
      - numba==0.60.0
      - numpy==1.23.5
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py==12.560.30
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.6.20
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - openai==1.46.1
      - opencv-python-headless==4.10.0.84
      - outlines==0.0.46
      - parso==0.8.4
      - partial-json-parser==0.2.1.1.post4
      - pexpect==4.9.0
      - pillow==10.4.0
      - pluggy==1.5.0
      - portalocker==2.10.1
      - prometheus-client==0.20.0
      - prometheus-fastapi-instrumentator==7.0.0
      - prompt-toolkit==3.0.47
      - protobuf==3.20.3
      - psutil==6.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - py-gfm==2.0.0
      - py-rouge==1.1
      - pyahocorasick==2.1.0
      - pyairports==2.1.1
      - pyarrow==17.0.0
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pycodestyle==2.12.1
      - pycountry==24.6.1
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pyflakes==3.2.0
      - pygments==2.18.0
      - pytest==8.3.2
      - pytest-datadir==1.5.0
      - pytest-regressions==2.5.0
      - python-dotenv==1.0.1
      - pyzmq==26.1.0
      - ray==2.36.0
      - referencing==0.35.1
      - requests-mock==1.12.1
      - responses==0.18.0
      - rpds-py==0.20.0
      - rsa==4.9
      - scikit-learn==1.5.1
      - scipy==1.14.0
      - sentencepiece==0.2.0
      - sh==2.0.7
      - smmap==5.0.1
      - sniffio==1.3.1
      - snowballstemmer==2.2.0
      - sphinx==5.1.1
      - sphinx-autodoc-typehints==1.10.3
      - sphinx-rtd-theme==2.0.0
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jquery==4.1
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - stack-data==0.6.3
      - starlette==0.38.5
      - subword-nmt==0.3.8
      - sympy==1.13.2
      - tensorboardx==2.5
      - textsearch==0.0.24
      - threadpoolctl==3.5.0
      - tiktoken==0.7.0
      - tomli==2.0.1
      - torch==2.4.0
      - torchtext==0.18.0
      - torchvision==0.19.0
      - tornado==6.4.1
      - tqdm==4.62.3
      - traitlets==5.14.3
      - triton==3.0.0
      - tzdata==2024.1
      - unidecode==1.3.8
      - untokenize==0.1.1
      - urllib3==1.26.19
      - uvicorn==0.30.6
      - uvloop==0.20.0
      - vllm==0.6.1.post2
      - vllm-flash-attn==2.6.1
      - watchfiles==0.24.0
      - wcwidth==0.2.13
      - websocket-client==1.8.0
      - websockets==13.0.1
      - xformers==0.0.27.post2
      - xxhash==3.4.1
prefix: /h/arashasg/miniconda3/envs/stereoset
