models:
  - name: "meta-llama/Llama-3.1-8B-Instruct"
    use_multi_gpu: True
  - name: "meta-llama/Meta-Llama-3-8B-Instruct"
    use_multi_gpu: True
  - name: "microsoft/Phi-3-mini-4k-instruct"
    use_multi_gpu: True
  - name: "microsoft/phi-2"
    use_multi_gpu: false
  - name: "google/gemma-2-9b-it"
    use_multi_gpu: true
  - name: "mistralai/Mistral-7B-Instruct-v0.3"
    use_multi_gpu: true
  - name: "microsoft/phi-4"
    use_multi_gpu: true
  - name: "meta-llama/Llama-4-Scout-17B-16E-Instruct"
    use_multi_gpu: true
  - name: "deepseek-ai/DeepSeek-R1-Distill-Llama-8B"
    use_multi_gpu: true
  - name: "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B"
    use_multi_gpu: true